// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#include "lvgl/lvgl.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern void ui_event_home(lv_event_t *e);
extern lv_obj_t *ui_home;
extern lv_obj_t *ui_emoji_container;
extern lv_obj_t *ui_chat_status_container;
extern lv_obj_t *ui_chat_status_label;
extern lv_obj_t *ui_audio_waveform_container;
// CUSTOM VARIABLES
void ui_home_screen_gif_enable(uint8_t enable);
void ui_home_screen_gif_update(const void *src);
void ui_home_screen_waveform_enable(uint8_t enable);
void ui_home_screen_waveform_start(float (*get_power_callback)(void));
void ui_home_screen_waveform_stop(void);
// app display functions
void ui_set_emotion(const char *emotion);
void ui_set_device_status(const char *status);
void ui_set_user_msg(const char *msg);
void ui_set_assistant_msg(const char *msg);
void ui_set_system_msg(const char *msg);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
