// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_top_container;
extern lv_obj_t * ui_middle_container;
extern lv_obj_t * ui_dev_status_container1;
extern lv_obj_t * ui_time_date_container;
extern lv_obj_t * ui_date_label;
extern lv_obj_t * ui_time_lable;
extern lv_obj_t * ui_icon_container;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_batter;
extern lv_obj_t * ui_dev_status_container2;
extern lv_obj_t * ui_label_container;
extern lv_obj_t * ui_volume_image;
extern lv_obj_t * ui_volume_label;
extern void ui_event_volume_slider(lv_event_t * e);
extern lv_obj_t * ui_volume_slider;
extern lv_obj_t * ui_bottom_container;
extern void ui_event_reset_button(lv_event_t * e);
extern lv_obj_t * ui_reset_button;
extern lv_obj_t * ui_reset_button_label;
// CUSTOM VARIABLES

void ui_setting_date_update(uint32_t year, uint32_t month, uint32_t day);
void ui_setting_time_update(uint32_t hour, uint32_t minute);
void ui_setting_wifi_update(uint8_t connected);
void ui_setting_batter_update(uint8_t charging, uint32_t percent);
void ui_setting_volume_slider_update(uint32_t value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
