// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _UI_COMP_AIMSGCONTAINER_H
#define _UI_COMP_AIMSGCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT aimsgcontainer
#define UI_COMP_AIMSGCONTAINER_AIMSGCONTAINER 0
#define UI_COMP_AIMSGCONTAINER_AI_HEAD 1
#define UI_COMP_AIMSGCONTAINER_AI_MSG 2
#define _UI_COMP_AIMSGCONTAINER_NUM 3
lv_obj_t * ui_aimsgcontainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
