// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _UI_COMP_USERMSGCONTAINER_H
#define _UI_COMP_USERMSGCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT usermsgcontainer
#define UI_COMP_USERMSGCONTAINER_USERMSGCONTAINER 0
#define UI_COMP_USERMSGCONTAINER_USER_MSG 1
#define UI_COMP_USERMSGCONTAINER_USER_HEAD 2
#define _UI_COMP_USERMSGCONTAINER_NUM 3
lv_obj_t * ui_usermsgcontainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
