// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _YOUR_CHAT_BOT_WECHAT_UI_COMP_HOOK_H
#define _YOUR_CHAT_BOT_WECHAT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_aimsgcontainer_create_hook(lv_obj_t * comp);
void ui_comp_systemmsgcontainer_create_hook(lv_obj_t * comp);
void ui_comp_usermsgcontainer_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
