// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#include "../ui.h"

void ui_comp_aimsgcontainer_create_hook(lv_obj_t * comp)
{
}

void ui_comp_system_msg_container_create_hook(lv_obj_t * comp)
{
}

void ui_comp_user_msg_container_create_hook(lv_obj_t * comp)
{
}

void ui_comp_systemmsgcontainer_create_hook(lv_obj_t * comp)
{
}

void ui_comp_usermsgcontainer_create_hook(lv_obj_t * comp)
{
}
