// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _UI_COMP_SYSTEMMSGCONTAINER_H
#define _UI_COMP_SYSTEMMSGCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT systemmsgcontainer
#define UI_COMP_SYSTEMMSGCONTAINER_SYSTEMMSGCONTAINER 0
#define UI_COMP_SYSTEMMSGCONTAINER_LABEL 1
#define _UI_COMP_SYSTEMMSGCONTAINER_NUM 2
lv_obj_t * ui_systemmsgcontainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
