// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _YOUR_CHAT_BOT_WECHAT_UI_H
#define _YOUR_CHAT_BOT_WECHAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home.h"
#include "screens/ui_setting.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_neutral_32_png);    // assets/image/emoji/twemoji32/neutral_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_happy_32_png);    // assets/image/emoji/twemoji32/happy_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_sad_32_png);    // assets/image/emoji/twemoji32/sad_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_angry_32_png);    // assets/image/emoji/twemoji32/angry_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_surprised_32_png);    // assets/image/emoji/twemoji32/surprised_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_confused_32_png);    // assets/image/emoji/twemoji32/confused_32.png
LV_IMG_DECLARE(ui_img_image_emoji_twemoji32_thinking_32_png);    // assets/image/emoji/twemoji32/thinking_32.png

LV_IMG_DECLARE(ui_img_image_icon_wifi_wifi_connect_30_png);    // assets/image/icon/WiFi/WiFi_connect_30.png
LV_IMG_DECLARE(ui_img_image_icon_wifi_wifi_disconnect_30_png);    // assets/image/icon/WiFi/WiFi_disconnect_30.png

LV_IMG_DECLARE(ui_img_image_heads_user_24_png);    // assets/image/heads/user_24.png
LV_IMG_DECLARE(ui_img_image_heads_ai_24_png);    // assets/image/heads/ai_24.png

LV_IMG_DECLARE(ui_img_image_icon_back_32_png);    // assets/image/icon/back_32.png
LV_IMG_DECLARE(ui_img_image_icon_volume_32_png);    // assets/image/icon/volume_32.png
LV_IMG_DECLARE(ui_img_image_icon_brightness_32_png);    // assets/image/icon/brightness_32.png

// FONTS
LV_FONT_DECLARE(ui_font_puhui_18_2);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
