// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void home_screen_loaded(lv_event_t * e);
void home_screen_unloaded(lv_event_t * e);
void setting_screen_loaded(lv_event_t * e);
void setting_screen_unloaded(lv_event_t * e);
void volume_bar_value_changed(lv_event_t * e);
void brightness_bar_value_changed(lv_event_t * e);
void theme_button_changed(lv_event_t * e);
void reset_button_callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
