// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background[2] = {0xF2F4F7, 0x1A1B26};
const ui_theme_variable_t _ui_theme_alpha_background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_statusBarBG[2] = {0x34C759, 0x1F4E3D};
const ui_theme_variable_t _ui_theme_alpha_statusBarBG[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_PrimaryText[2] = {0x2C3E50, 0xF0F2F5};
const ui_theme_variable_t _ui_theme_alpha_PrimaryText[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

