// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lang_config.h"

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home.h"
#include "screens/ui_setting.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_image_battery_battercharging_png);    // assets/image/battery/batterCharging.png
LV_IMG_DECLARE(ui_img_image_battery_battery100_png);    // assets/image/battery/battery100.png
LV_IMG_DECLARE(ui_img_image_battery_battery60_png);    // assets/image/battery/battery60.png
LV_IMG_DECLARE(ui_img_image_battery_battery50_png);    // assets/image/battery/battery50.png
LV_IMG_DECLARE(ui_img_image_battery_battery20_png);    // assets/image/battery/battery20.png

LV_IMG_DECLARE(ui_img_image_volume_volume_png);    // assets/image/volume/volume.png

LV_IMG_DECLARE(ui_img_image_wifi_wifi_30_png);    // assets/image/wifi/wifi_30.png
LV_IMG_DECLARE(ui_img_image_wifi_wifi_disconnect_30_png);    // assets/image/wifi/wifi_disconnect_30.png

// FONTS
LV_FONT_DECLARE(ui_font_mont_82);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
