// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: your_chat_bot_WeChat

#ifndef UI_SETTING_H
#define UI_SETTING_H

#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_setting_status_bar;
extern void ui_event_setting_emoji(lv_event_t * e);
extern lv_obj_t * ui_setting_emoji;
extern lv_obj_t * ui_setting_status_label;
extern lv_obj_t * ui_setting_icon;
extern lv_obj_t * ui_setting_setting_container;
extern lv_obj_t * ui_setting_time;
extern lv_obj_t * ui_setting_date;
extern lv_obj_t * ui_setting_volume_container;
extern lv_obj_t * ui_setting_volume_label;
extern lv_obj_t * ui_setting_volume_icon_container;
extern lv_obj_t * ui_setting_volume_image;
extern void ui_event_setting_volume_slider(lv_event_t * e);
extern lv_obj_t * ui_setting_volume_slider;
extern lv_obj_t * ui_setting_brightness_container;
extern lv_obj_t * ui_setting_brightness_label;
extern lv_obj_t * ui_setting_brightness_icon_container;
extern lv_obj_t * ui_setting_brightness_image;
extern void ui_event_setting_brightness_slider(lv_event_t * e);
extern lv_obj_t * ui_setting_brightness_slider;
extern lv_obj_t * ui_setting_theme_container;
extern lv_obj_t * ui_setting_theme_label;
extern void ui_event_setting_theme_switch(lv_event_t * e);
extern lv_obj_t * ui_setting_theme_switch;
extern void ui_event_setting_reset_button(lv_event_t * e);
extern lv_obj_t * ui_setting_reset_button;
extern lv_obj_t * ui_setting_reset_button_label;
// CUSTOM VARIABLES

void ui_setting_date_update(uint32_t year, uint32_t month, uint32_t day);
void ui_setting_time_update(uint32_t hour, uint32_t minute);
void ui_setting_volume_slider_update(uint32_t value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

